apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: example-app
  environment: dev
# Optional: Add config maps, secrets, patches
# configMapGenerator:
# secretGenerator:
# patchesStrategicMerge:
